name: hello_network_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  blur: ^3.1.0
  camera: ^0.10.5+2
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_local_notifications: ^14.1.1
  flutter_native_timezone_updated_gradle: ^2.0.3
  fluttericon: ^2.0.0
  http: ^0.13.6
  path: ^1.8.2
  path_provider: ^2.0.15
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  socket_io_client: ^2.0.2
  timezone: ^0.9.2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - graphics/bg/
    - graphics/profile/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: PoppinsMedium
      fonts:
        - asset: fonts/Poppins-Medium.ttf