name: hello_network_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  blur: ^3.1.0
  flutter:
    sdk: flutter
  fluttericon: ^2.0.0
  provider: ^6.0.5
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - graphics/bg/
    - graphics/profile/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: PoppinsMedium
      fonts:
        - asset: fonts/Poppins-Medium.ttf